# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bitsflea_pb2 as bitsflea__pb2


class BitsFleaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/bitsflea.BitsFlea/Register',
        request_serializer=bitsflea__pb2.RegisterRequest.SerializeToString,
        response_deserializer=bitsflea__pb2.RegisterReply.FromString,
        )
    self.SendSmsCode = channel.unary_unary(
        '/bitsflea.BitsFlea/SendSmsCode',
        request_serializer=bitsflea__pb2.SmsRequest.SerializeToString,
        response_deserializer=bitsflea__pb2.BaseReply.FromString,
        )
    self.RefreshToken = channel.unary_unary(
        '/bitsflea.BitsFlea/RefreshToken',
        request_serializer=bitsflea__pb2.RefreshTokenRequest.SerializeToString,
        response_deserializer=bitsflea__pb2.RefreshTokenReply.FromString,
        )
    self.Referral = channel.unary_unary(
        '/bitsflea.BitsFlea/Referral',
        request_serializer=bitsflea__pb2.EosidRequest.SerializeToString,
        response_deserializer=bitsflea__pb2.BaseReply.FromString,
        )


class BitsFleaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendSmsCode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RefreshToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Referral(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BitsFleaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=bitsflea__pb2.RegisterRequest.FromString,
          response_serializer=bitsflea__pb2.RegisterReply.SerializeToString,
      ),
      'SendSmsCode': grpc.unary_unary_rpc_method_handler(
          servicer.SendSmsCode,
          request_deserializer=bitsflea__pb2.SmsRequest.FromString,
          response_serializer=bitsflea__pb2.BaseReply.SerializeToString,
      ),
      'RefreshToken': grpc.unary_unary_rpc_method_handler(
          servicer.RefreshToken,
          request_deserializer=bitsflea__pb2.RefreshTokenRequest.FromString,
          response_serializer=bitsflea__pb2.RefreshTokenReply.SerializeToString,
      ),
      'Referral': grpc.unary_unary_rpc_method_handler(
          servicer.Referral,
          request_deserializer=bitsflea__pb2.EosidRequest.FromString,
          response_serializer=bitsflea__pb2.BaseReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bitsflea.BitsFlea', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
